import './globals.css'

import React from 'react'
import { Roboto } from 'next/font/google'
import StyledComponentsRegistry from '@/lib/registry'
import MyApp from './_app'

const inter = Roboto({
  weight: ['300', '400', '700', '900'],
  subsets: ['cyrillic'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <div style={{ height: '100vh' }}>
            <MyApp>{children}</MyApp>
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
